# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d4a6ef09360254f3392dff157b0c8979884e35ce066232552e73b690b31c025cfaf1171e20f540009b5a78efa6b9890024ee9e49f2267a06b34f281da766ed5

test:
  secret_key_base: dec84643798a5a0d89a0fd9d50f7470b888c40fbe665c6c31278c097312eb526c29b6b961d5115e9b1ec06877bb5ef652072f54b6f5d17e06c38ea317932edcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
